$("#input").on('keyup', function (e) {
  if (e.key === 'Enter' || e.keyCode === 13) {
    window.location.href="https://youtube.com"
  }
});
$("#youtubel").on('click', () => window.location.href="https://youtube.com")
$("#redditl").on('click', () => window.location.href = "https://reddit.com")
$("#xl").on('click', () => window.location.href = "https://x.com")
$("#discordl").on('click', () => window.location.href = "https://discord.com")
$("#robloxl").on('click', () => window.location.href = "https://roblox.com")

let quotes = [
  "Why do today what you can put off until tomorrow?",
  "The best ideas come when you're avoiding work.",
  "Procrastination is the art of keeping up with yesterday.",
  "Never put off until tomorrow what you can put off indefinitely.",
  "Hard work pays off eventually... but procrastination pays off now.",
  "You can't fail if you never start!",
  "Slow and steady wins the race-so why even leave the starting line?",
  "If it's important, it will get done... eventually.",
  "The road to success is under construction, so take a detour and relax.",
  "A journey of a thousand miles begins with a single nap.",
  "Success is for those who rush in. Legends wait until the last second.",
  "Time you enjoy wasting is not wasted time.",
  "The future is full of possibilities-so let Future You handle them.",
  "Nothing great was ever accomplished by someone who started early.",
  "The best time to start was yesterday. The second-best time is never.",
  "Be so busy doing nothing that you forget to worry about everything.",
  "You don't need a plan when you have good excuses.",
  "Why stress about deadlines when they'll pass on their own?",
  "If something is worth doing, it's worth delaying.",
  "A little delay never hurt anyone-except maybe your GPA.",
  "Dream big, work later.",
  "Procrastination isn't a problem, it's a lifestyle.",
  "Some call it laziness; I call it efficiency in relaxation.",
  "Deadlines are just gentle suggestions.",
  "Tomorrow is the busiest day of the week.",
  "The sooner you start, the sooner you'll have to finish.",
  "If you're going to do something, you might as well do it last minute for the adrenaline rush.",
  "Don't put all your eggs in one basket-put them on the back burner instead.",
  "Patience is a virtue, and procrastination is its best friend.",
  "Do your best... to put it off as long as possible.",
  "The key to success is to start before you're ready-so just never be ready.",
  "Why be early when you can be fashionably late?",
  "Work smarter, not harder-by avoiding work altogether.",
  "Your problems will still be there tomorrow, so don't stress about them today.",
  "Good things come to those who wait... and wait... and wait.",
  "If you ignore it long enough, maybe it will go away.",
  "Procrastination is self-care, and I care about myself a lot.",
  "Some things are better left undone-especially things you don't want to do.",
  "Life is too short to rush things... or to do them on time.",
  "If you don't start, you can't mess up.",
  "The later you do it, the faster it gets done.",
  "Everything is possible-especially postponing responsibilities.",
  "If you can't be productive, be really good at avoiding it.",
  "Why finish today when you can complain about it for another week first?",
  "Life's too short for stress, so let Future You handle it.",
  "Take things one step at a time... starting next month.",
  "A job well delayed is a job half done.",
  "There's a fine line between efficiency and procrastination, and I choose to stay on the fun side.",
  "Don't rush success-let it come to you while you nap.",
  "Some people work well under pressure. I work well under Netflix and snacks.",
  "The best work happens at the last possible second-so wait for it.",
  "Procrastination is the universe's way of telling you to chill.",
  "Why waste time working when you can waste time relaxing?",
  "Good things come to those who wait until the last minute.",
  "The best way to finish something is to not start at all.",
  "Deadlines are just society's way of killing the creative process.",
  "When in doubt, put it off.",
  "If you ignore it long enough, it might resolve itself.",
  "Delaying is just a way of making sure you still have something to do later.",
  "Every masterpiece starts with a blank page-and stays that way for weeks.",
  "A well-rested mind is a productive mind, so take a nap first.",
  "Some people make things happen. Others watch things happen. I take a nap and wake up confused.",
  "If it's urgent, it will eventually become someone else's problem.",
  "The world wasn't built in a day-so why should your essay be?",
  "Hard work never killed anyone, but why take the risk?",
  "If at first, you don't succeed, redefine success to mean 'trying later.'",
  "The best way to be on time is to redefine 'on time.'",
  "If something needs to be done, start by distracting yourself from it.",
  "Good things come to those who procrastinate... probably.",
  "You can't be overwhelmed if you refuse to acknowledge the task exists.",
  "Why be ahead of schedule when you can live dangerously close to the deadline?",
  "A well-procrastinated task is a job almost done.",
  "Everything is better when done later-except maybe taxes.",
  "Your future self will thank you for not doing this today... or hate you, but that's Future You's problem.",
  "A watched deadline never moves-so just stop looking at it.",
  "There's always tomorrow, and if there isn't, then it really didn't matter anyway.",
  "If you do it now, you'll just have to find something else to procrastinate on later.",
  "Some people are productive; I prefer to be inspirationally lazy.",
  "Start strong, finish... whenever.",
  "Procrastination: Because coffee tastes better when you're panicking.",
  "If at first, you don't succeed, try avoiding it entirely.",
  "Take it slow, or better yet, don't take it at all.",
  "Work will always be there, but naps won't wait.",
  "Efficiency is doing nothing until absolutely necessary.",
  "The best way to complete a task is to delete it from your to-do list.",
  "Why stress when you can suppress?",
  "The best productivity hack is to redefine ‘productive' as ‘watching cat videos.'",
  "I work best under pressure, which is why I wait until the last second.",
  "If you never try, you can never fail.",
  "Perfection takes time, so I'm just giving it all the time in the world.",
  "If you ignore the deadline, maybe it will go away.",
  "The universe rewards those who wait... or at least distracts them long enough to forget the task.",
  "Stay calm and procrastinate on.",
  "The greatest risk in life is actually starting something.",
  "If it can be done today, it can probably be done next week.",
  "Motivation is for people who start things early-procrastination is for visionaries.",
  "A deadline missed is a lesson in self-care.",
  "Success comes to those who wait... or at least those who panic at the last minute.",
  "Why work when you can daydream about working?",
  "Don't fear failure-fear finishing things too soon!"
];
$("#quote").html(quotes[Math.floor(Math.random() * quotes.length)])
